zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    ships-service:
      path: /ships/**
      stripPrefix: false
      sensitiveHeaders:

    shipments-service:
      path: /shipments/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:

    deliveries-service:
      path: /deliveries/**
      serviceId: statistics-service
      stripPrefix: false
      sensitiveHeaders:

    users-service:
      path: /users/**
      serviceId: notification-service
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000